CREATE TABLE IF NOT EXISTS temperatur_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    måler_navn TEXT NOT NULL,
    temperatur REAL NOT NULL,
    logget_tid DATETIME DEFAULT CURRENT_TIMESTAMP
);

